# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :stagging do |stagging|
    stagging.vm.hostname = "stagging"
    stagging.vm.network :private_network, ip: "192.168.33.90"
    stagging.vm.provision "shell", inline: <<-SHELL 
      curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
      sudo yum install vim unzip nodejs -y 
    SHELL
  end
  config.vm.define :production do |production|
    production.vm.hostname = "production"
    production.vm.network :private_network, ip: "192.168.33.100"
    production.vm.provision "shell", inline: <<-SHELL 
      curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
      sudo yum install vim unzip nodejs -y
    SHELL
  end
end 
