# -*- mode: ruby -*-
 # vi: set ft=ruby :
 Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1804"
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define :master do |master|
    master.vm.box_check_update = false
    master.vm.hostname = "master"
    master.vm.network :private_network, ip: "192.168.33.201"
  end

  config.vm.define :node1 do |node1|
    node1.vm.box_check_update = false
    node1.vm.hostname = "node1"
    node1.vm.network :private_network, ip: "192.168.33.202"
  end

  config.vm.define :node2 do |node2|
    node2.vm.box_check_update = false
    node2.vm.hostname = "node2"
    node2.vm.network :private_network, ip: "192.168.33.203"
  end

end
