# -*- mode: ruby -*-
 # vi: set ft=ruby :
 Vagrant.configure("2") do |config|
    config.vm.box = "geerlingguy/centos7"
 
    config.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
 
    config.vm.define :control do |control|
      control.vm.hostname = "control"
      control.vm.network :private_network, ip: "192.168.100.10"
      control.vm.provision "shell", inline: <<-SHELL
        sudo yum install -y ansible
        sudo yum install -y vim 
      SHELL
    end
 
    config.vm.define :web do |web|
      web.vm.hostname = "node1"
      web.vm.network :private_network, ip: "192.168.100.20"
    end
 
    config.vm.define :db do |db|
      db.vm.hostname = "node2"
      db.vm.network :private_network, ip: "192.168.100.30"
    end
 
  end