events {
}
http {
    include /etc/nginx/mime.types;

    upstream MYAPP1 {
        #server {{backendsrv[0]}};
        {%for item in backendsrv %}
        server {{ item }};
        {%endfor%}
    }
    server {
    listen 80;

    server_name zkt.vn;

    location / {
        proxy_pass "http://MYAPP1";
    }
    }
}
